version: '3.8'
services:
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - database
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: postgres:alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      environment: 
      POSTGRES_USER: ${POSTGRES_USER:-admin} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123} 
      POSTGRES_DB: ${POSTGRES_DB:-my_database}
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    command: redis-server --requirepass "${REDIS_PASSWORD:-redispass123}"
    networks:
      - app_network
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass123", "PING"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
