apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-challenge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Dacru/DevOps/tree/main'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

